### ISSUE TITLE
Weird behavior with data-theme="white"

### ISSUE THREAD

**Issue by zopyx** [nextapps-de/spotlight#25]
I have added spotlight on my site here:

https://www.print-css.rocks/lesson/lesson-multi-columns

Clicking on an image sometimes results with a black, sometimes with a background although data-theme="white" is set for all image links.

**Comment by crunchpaste** [comment]
Had the same problem a few months ago. I know it's not a proper solution but managed to find a workaround that worked for men. Just removed the `data-theme="white"` and included a few `!important` tags in my CSS file. It's not the cleanest solution but here you go:

```css

#spotlight .arrow,
#spotlight .footer,
#spotlight .header,
#spotlight .preloader,
#spotlight .progress {
    filter:invert(1) !important
}

#spotlight {
    color: #D2D3D4 !important;
    background-color: #fff !important;
    font-family: Helvetica, Arial, sans-serif !important;
}
```

Then again I would probably advise you to find a new lightbox library as this one seems to be abandoned almost an year ago.
