### ISSUE TITLE
I have an issue with iframe

### ISSUE THREAD

**Issue by theodore74** [nextapps-de/spotlight#37]
I implement iframe instead of frameset.
main.html is the main html of spotlight.
Then I found a problem while clicking an image, the [X] button will be outside the screen. I can not click it to close image.
May you fix this?
(For now, I just modify "width: 100%;" to "width: 90%" to avoid the error , but iframe will have one extra scrollbar .)

        <style type="text/css">        
		#frameTop
        {
            position: absolute;
            top: 0;
            left: 0;
            height: 100px;
            width: 100%;
            overflow: hidden;
            vertical-align: middle;
        }

        #frameContentLeft
        {
            position: fixed;
            top: 0;
            left: 0;
            height: 100%;
            width: auto;
            overflow: hidden;
            vertical-align: top;
            background-color: #777;
        }

        #frameContentRight
        {
            position: absolute;
            left: 120px;
            top: 0;
            height: 100%;
            width: 100%;
            right: 0;
            bottom: 0;
            overflow: hidden;
            background: #fff;
			
        }

        </style>

    </head>
    <body>    

    <div>
        <iframe id="frameContentLeft" src="menu.html"></iframe>
        <iframe id="frameContentRight" src="main.html"></iframe>
    </div>

**Comment by ts-thomas** [comment]
Please check again with the new verison >= 0.7.0. The spotlight viewport will overlay the scrollbar by default, because that is the most common scenario. When you need some modification you have to apply them by custom CSS.

That should do the trick (does not overlay the frame width):
```css
#spotlight{
    position: absolute;
    width: auto;
    left: 0;
}
```

To prevent scrollbar overlay completely you may need to add this additionally:
```css
.hide-scrollbars::-webkit-scrollbar {
    width: auto;
}
.hide-scrollbars{
    overflow: auto;
    -ms-overflow-style: auto;
}
```
