### ISSUE TITLE
Disabling fullscreen not works

### ISSUE THREAD

**Issue by adaniello** [nextapps-de/spotlight#65]
If i want hide "fullscreen" icon, eg. via "fullscreen" data attribute by setting it to "false" , i can't.

You can check this issue also in your demo https://nextapps-de.github.io/spotlight/ at the section "Choose Controls (Toolbar)": checkbox not has effect.

Thanks

**Comment by mirumirumi** [comment]
Yes, I have same problem.
For now, I'm doing this: 
```css
.spl-fullscreen {
  display: none !important;
}
```
